class TimeTablModel {
  String day;
  List<PeriodModel> periodsList;
  TimeTablModel({
    required this.day,
    required this.periodsList,
  });
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['day'] = day;
    List<Map<String, dynamic>> jsonEventsList = [];
    for (PeriodModel element in periodsList) {
      jsonEventsList.add(element.toJson());
    }
    data['periodsList'] = jsonEventsList;
    return data;
  }
}

class PeriodModel {
  String periodType;
  String startTime;
  String endTime;

  String subjectName;
  String subjectCode;
  String subjectTeacher;
  int subjectCount;
  PeriodModel(
      {required this.periodType,
      required this.startTime,
      required this.endTime,
      required this.subjectCode,
      required this.subjectName,
      required this.subjectTeacher,
      required this.subjectCount});

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['periodType'] = periodType;
    data['startTime'] = startTime;
    data['endTime'] = endTime;
    data['subjectCount'] = subjectCount;
    data['subjectName'] = subjectName;
    data['subjectCode'] = subjectCode;
    data['subjectTeacher'] = subjectTeacher;
    return data;
  }
}

List<TimeTablModel> timetableList = [
  //MONDAY
  TimeTablModel(day: "MON", periodsList: [
    PeriodModel(
      periodType: "period",
      startTime: "09:00 AM",
      endTime: "09:45 AM",
      subjectCode: "PH4561",
      subjectName: "Physics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 1,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "09:45 AM",
      endTime: "10:30 AM",
      subjectCode: "MA6532",
      subjectName: "Mathematics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 2,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "10:30 AM",
      endTime: "10:45 AM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "10:45 AM",
      endTime: "11:30 AM",
      subjectCode: "EN6532",
      subjectName: "English",
      subjectTeacher: "Tyler Duren",
      subjectCount: 3,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "11:30 AM",
      endTime: "12:15 PM",
      subjectCode: "TM6532",
      subjectName: "Tamil",
      subjectTeacher: "Tyler Duren",
      subjectCount: 4,
    ),
    PeriodModel(
      periodType: "lunch",
      startTime: "12:15 PM",
      endTime: "01:00 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:00 PM",
      endTime: "01:45 PM",
      subjectCode: "CH6532",
      subjectName: "Chemistry",
      subjectTeacher: "Tyler Duren",
      subjectCount: 5,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:45 PM",
      endTime: "02:30 PM",
      subjectCode: "BG6532",
      subjectName: "Biology",
      subjectTeacher: "Tyler Duren",
      subjectCount: 6,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "02:30 PM",
      endTime: "02:45 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "02:45 PM",
      endTime: "03:30 PM",
      subjectCode: "CS4523",
      subjectName: "Computer Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 7,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "03:30 PM",
      endTime: "04:15 PM",
      subjectCode: "EVS456",
      subjectName: "Environmental Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 8,
    ),
    PeriodModel(
      periodType: "finish",
      startTime: "04:15 PM",
      endTime: "04:15 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    )
  ]),
  //TUESDAY
  TimeTablModel(day: "TUE", periodsList: [
    PeriodModel(
      periodType: "period",
      startTime: "09:00 AM",
      endTime: "09:45 AM",
      subjectCode: "PH4561",
      subjectName: "Physics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 1,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "09:45 AM",
      endTime: "10:30 AM",
      subjectCode: "MA6532",
      subjectName: "Mathematics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 2,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "10:30 AM",
      endTime: "10:45 AM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "10:45 AM",
      endTime: "11:30 AM",
      subjectCode: "EN6532",
      subjectName: "English",
      subjectTeacher: "Tyler Duren",
      subjectCount: 3,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "11:30 AM",
      endTime: "12:15 PM",
      subjectCode: "TM6532",
      subjectName: "Tamil",
      subjectTeacher: "Tyler Duren",
      subjectCount: 4,
    ),
    PeriodModel(
      periodType: "lunch",
      startTime: "12:15 PM",
      endTime: "01:00 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:00 PM",
      endTime: "01:45 PM",
      subjectCode: "CH6532",
      subjectName: "Chemistry",
      subjectTeacher: "Tyler Duren",
      subjectCount: 5,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:45 PM",
      endTime: "02:30 PM",
      subjectCode: "BG6532",
      subjectName: "Biology",
      subjectTeacher: "Tyler Duren",
      subjectCount: 6,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "02:30 PM",
      endTime: "02:45 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "02:45 PM",
      endTime: "03:30 PM",
      subjectCode: "CS4523",
      subjectName: "Computer Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 7,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "03:30 PM",
      endTime: "04:15 PM",
      subjectCode: "EVS456",
      subjectName: "Environmental Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 8,
    ),
    PeriodModel(
      periodType: "finish",
      startTime: "04:15 PM",
      endTime: "04:15 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    )
  ]),
  //WENESDAY
  TimeTablModel(day: "WED", periodsList: [
    PeriodModel(
      periodType: "period",
      startTime: "09:00 AM",
      endTime: "09:45 AM",
      subjectCode: "PH4561",
      subjectName: "Physics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 1,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "09:45 AM",
      endTime: "10:30 AM",
      subjectCode: "MA6532",
      subjectName: "Mathematics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 2,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "10:30 AM",
      endTime: "10:45 AM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "10:45 AM",
      endTime: "11:30 AM",
      subjectCode: "EN6532",
      subjectName: "English",
      subjectTeacher: "Tyler Duren",
      subjectCount: 3,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "11:30 AM",
      endTime: "12:15 PM",
      subjectCode: "TM6532",
      subjectName: "Tamil",
      subjectTeacher: "Tyler Duren",
      subjectCount: 4,
    ),
    PeriodModel(
      periodType: "lunch",
      startTime: "12:15 PM",
      endTime: "01:00 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:00 PM",
      endTime: "01:45 PM",
      subjectCode: "CH6532",
      subjectName: "Chemistry",
      subjectTeacher: "Tyler Duren",
      subjectCount: 5,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:45 PM",
      endTime: "02:30 PM",
      subjectCode: "BG6532",
      subjectName: "Biology",
      subjectTeacher: "Tyler Duren",
      subjectCount: 6,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "02:30 PM",
      endTime: "02:45 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "02:45 PM",
      endTime: "03:30 PM",
      subjectCode: "CS4523",
      subjectName: "Computer Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 7,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "03:30 PM",
      endTime: "04:15 PM",
      subjectCode: "EVS456",
      subjectName: "Environmental Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 8,
    ),
    PeriodModel(
      periodType: "finish",
      startTime: "04:15 PM",
      endTime: "04:15 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    )
  ]),
  //THURSDAY
  TimeTablModel(day: "THU", periodsList: [
    PeriodModel(
      periodType: "period",
      startTime: "09:00 AM",
      endTime: "09:45 AM",
      subjectCode: "PH4561",
      subjectName: "Physics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 1,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "09:45 AM",
      endTime: "10:30 AM",
      subjectCode: "MA6532",
      subjectName: "Mathematics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 2,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "10:30 AM",
      endTime: "10:45 AM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "10:45 AM",
      endTime: "11:30 AM",
      subjectCode: "EN6532",
      subjectName: "English",
      subjectTeacher: "Tyler Duren",
      subjectCount: 3,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "11:30 AM",
      endTime: "12:15 PM",
      subjectCode: "TM6532",
      subjectName: "Tamil",
      subjectTeacher: "Tyler Duren",
      subjectCount: 4,
    ),
    PeriodModel(
      periodType: "lunch",
      startTime: "12:15 PM",
      endTime: "01:00 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:00 PM",
      endTime: "01:45 PM",
      subjectCode: "CH6532",
      subjectName: "Chemistry",
      subjectTeacher: "Tyler Duren",
      subjectCount: 5,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:45 PM",
      endTime: "02:30 PM",
      subjectCode: "BG6532",
      subjectName: "Biology",
      subjectTeacher: "Tyler Duren",
      subjectCount: 6,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "02:30 PM",
      endTime: "02:45 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "02:45 PM",
      endTime: "03:30 PM",
      subjectCode: "CS4523",
      subjectName: "Computer Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 7,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "03:30 PM",
      endTime: "04:15 PM",
      subjectCode: "EVS456",
      subjectName: "Environmental Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 8,
    ),
    PeriodModel(
      periodType: "finish",
      startTime: "04:15 PM",
      endTime: "04:15 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    )
  ]),
  //FRIDAY
  TimeTablModel(day: "FRI", periodsList: [
    PeriodModel(
      periodType: "period",
      startTime: "09:00 AM",
      endTime: "09:45 AM",
      subjectCode: "PH4561",
      subjectName: "Physics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 1,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "09:45 AM",
      endTime: "10:30 AM",
      subjectCode: "MA6532",
      subjectName: "Mathematics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 2,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "10:30 AM",
      endTime: "10:45 AM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "10:45 AM",
      endTime: "11:30 AM",
      subjectCode: "EN6532",
      subjectName: "English",
      subjectTeacher: "Tyler Duren",
      subjectCount: 3,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "11:30 AM",
      endTime: "12:15 PM",
      subjectCode: "TM6532",
      subjectName: "Tamil",
      subjectTeacher: "Tyler Duren",
      subjectCount: 4,
    ),
    PeriodModel(
      periodType: "lunch",
      startTime: "12:15 PM",
      endTime: "01:00 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:00 PM",
      endTime: "01:45 PM",
      subjectCode: "CH6532",
      subjectName: "Chemistry",
      subjectTeacher: "Tyler Duren",
      subjectCount: 5,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:45 PM",
      endTime: "02:30 PM",
      subjectCode: "BG6532",
      subjectName: "Biology",
      subjectTeacher: "Tyler Duren",
      subjectCount: 6,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "02:30 PM",
      endTime: "02:45 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "02:45 PM",
      endTime: "03:30 PM",
      subjectCode: "CS4523",
      subjectName: "Computer Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 7,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "03:30 PM",
      endTime: "04:15 PM",
      subjectCode: "EVS456",
      subjectName: "Environmental Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 8,
    ),
    PeriodModel(
      periodType: "finish",
      startTime: "04:15 PM",
      endTime: "04:15 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    )
  ]),
  //SATURDAY
  TimeTablModel(day: "SAT", periodsList: [
    PeriodModel(
      periodType: "period",
      startTime: "09:00 AM",
      endTime: "09:45 AM",
      subjectCode: "PH4561",
      subjectName: "Physics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 1,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "09:45 AM",
      endTime: "10:30 AM",
      subjectCode: "MA6532",
      subjectName: "Mathematics",
      subjectTeacher: "Tyler Duren",
      subjectCount: 2,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "10:30 AM",
      endTime: "10:45 AM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "10:45 AM",
      endTime: "11:30 AM",
      subjectCode: "EN6532",
      subjectName: "English",
      subjectTeacher: "Tyler Duren",
      subjectCount: 3,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "11:30 AM",
      endTime: "12:15 PM",
      subjectCode: "TM6532",
      subjectName: "Tamil",
      subjectTeacher: "Tyler Duren",
      subjectCount: 4,
    ),
    PeriodModel(
      periodType: "lunch",
      startTime: "12:15 PM",
      endTime: "01:00 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:00 PM",
      endTime: "01:45 PM",
      subjectCode: "CH6532",
      subjectName: "Chemistry",
      subjectTeacher: "Tyler Duren",
      subjectCount: 5,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "01:45 PM",
      endTime: "02:30 PM",
      subjectCode: "BG6532",
      subjectName: "Biology",
      subjectTeacher: "Tyler Duren",
      subjectCount: 6,
    ),
    PeriodModel(
      periodType: "break",
      startTime: "02:30 PM",
      endTime: "02:45 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "02:45 PM",
      endTime: "03:30 PM",
      subjectCode: "CS4523",
      subjectName: "Computer Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 7,
    ),
    PeriodModel(
      periodType: "period",
      startTime: "03:30 PM",
      endTime: "04:15 PM",
      subjectCode: "EVS456",
      subjectName: "Environmental Science",
      subjectTeacher: "Tyler Duren",
      subjectCount: 8,
    ),
    PeriodModel(
      periodType: "finish",
      startTime: "04:15 PM",
      endTime: "04:15 PM",
      subjectCode: "",
      subjectName: "",
      subjectTeacher: "",
      subjectCount: 0,
    )
  ])
];
